version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always  # Автоматический перезапуск контейнера MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Подключаем volume к MongoDB для сохранения данных
      - ./mongod.conf:/etc/mongod.conf  # Подключаем конфигурационный файл
    command: mongod --config /etc/mongod.conf  # Используем конфигурационный файл
    networks:
      - app-network

  server:
    build: .
    container_name: local_server
    restart: always  # Автоматический перезапуск контейнера сервера
    ports:
      - "33000:33000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - JWT_SECRET=your_jwt_secret_here
      - REGISTRATION_SECRET_CODE=your_registration_code_here

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
